--- Default only `nil` values to a given default value
---   Almost equivalent with `or`, but does not default false
---@param value any Value that might be `nil`
---@param _default any Value to default to if value is 'nil'
---@return any
function Default(value, _default)
	if value == nil then
		return _default
	end
	return value
end

function Dump(t)
	local ty = type(t)
	if ty == "nil" then
		io.write("nil")
	elseif ty == "string" then
		io.write('"' .. t .. '"')
	elseif ty == "table" then
		io.write("{")
		local is_first = true
		for key, value in pairs(t) do
			if not is_first then
				io.write(", ")
			end
			is_first = false
			if type(key) ~= "number" then
				io.write(string.format("%s = ", key))
			end
			Dump(value)
		end
		io.write("}")
	else
		io.write(string.format("%s", t))
	end
end

--- Turns a Dictionary into an array by omitting the keys
---@param t table
---@return table
function Values(t)
	local result = {}
	for _, value in pairs(t) do
		table.insert(result, value)
	end
	return result
end

--- Reads a file and immediately writes it to io.write, useful for template files
--- @param file string
function PipeFile(file)
	local inp = assert(io.open(file, "r"))
	io.write(inp:read("*all"))
	inp:close()
end

function HeaderGuardStart(guard)
	io.write("// This file has been autogenerated.\n")
	io.write("#ifndef " .. guard .. "\n")
	io.write("#define " .. guard .. "\n")
	io.write("\n")
end

function HeaderGuardEnd(guard)
	io.write("#endif // " .. guard .. "\n")
end

function SourceBegin(header)
	io.write("// This file has been autogenerated.\n")
	io.write('#include "' .. header .. '"\n')
end

function FindTexturesIter()
	-- NOTE: This probably won't work on windows like systems >:(
	local process = assert(io.popen('find ./assets/textures -iname "*.png" | sort', "r"))
	return process:lines("l")
end
