require("meta.utils")

IS_HEADER = false

function FunctionBegin(return_type, fn_name, ...)
	local args = { ... }
	if not IS_HEADER then
		io.write("inline ")
	end
	local arg_str = table.concat(args, ", ")
	io.write(string.format("%s %s(%s)", return_type, fn_name, arg_str))
	if IS_HEADER then
		io.write(";\n")
	else
		io.write(" {\n")
	end
end

function FunctionEnd()
	if not IS_HEADER then
		io.write("}\n")
	end
end

function MathHeaderBegin(header_guard)
	HeaderGuardStart(header_guard)
	IS_HEADER = true
end

function MathHeaderEnd(header_guard)
	HeaderGuardEnd(header_guard)
end

function MathSourceBegin(header_file, includes)
	IS_HEADER = false
	io.write("// This file has been autogenerated using meta/math/generate.lua\n")
	io.write('#include "', header_file, '"\n')
	for _, value in ipairs(includes) do
		io.write("#include ", value, "\n")
	end
end

function MathSourceEnd()
	IS_HEADER = false
end
