// This file has been autogenerated.
#ifndef LINALG_H
#define LINALG_H

float fast_inv_sqrt(float v);


// ////// Vec2i //////
typedef union {
	struct { int x; int y; };
	int v[2];
} Vec2i;

Vec2i vec2i_add(Vec2i a, Vec2i b);
Vec2i vec2i_sub(Vec2i a, Vec2i b);
Vec2i vec2i_scale(Vec2i a, int scale);
int vec2i_dot(Vec2i a, Vec2i b);
int vec2i_lengthsqr(Vec2i vector);
Vec2i vec2i_normalize(Vec2i vector);
Vec2i vec2i_min(Vec2i a, Vec2i b);
Vec2i vec2i_max(Vec2i a, Vec2i b);
void vec2i_print(Vec2i vector);
#define VEC2I_ZERO 	((Vec2i){ .x = 0, .y = 0, })
#define VEC2I_ONE 	((Vec2i){ .x = 1, .y = 1, })
#define VEC2I_LEFT 	((Vec2i){ .x = -1, .y = 0, })
#define VEC2I_RIGHT 	((Vec2i){ .x = 1, .y = 0, })
#define VEC2I_UP 	((Vec2i){ .x = 0, .y = -1, })
#define VEC2I_DOWN 	((Vec2i){ .x = 0, .y = 1, })


// ////// Vec3i //////
typedef union {
	struct { int x; int y; int z; };
	int v[3];
} Vec3i;

Vec3i vec3i_add(Vec3i a, Vec3i b);
Vec3i vec3i_sub(Vec3i a, Vec3i b);
Vec3i vec3i_scale(Vec3i a, int scale);
int vec3i_dot(Vec3i a, Vec3i b);
int vec3i_lengthsqr(Vec3i vector);
Vec3i vec3i_normalize(Vec3i vector);
Vec3i vec3i_min(Vec3i a, Vec3i b);
Vec3i vec3i_max(Vec3i a, Vec3i b);
void vec3i_print(Vec3i vector);
#define VEC3I_ZERO 	((Vec3i){ .x = 0, .y = 0, .z = 0, })
#define VEC3I_ONE 	((Vec3i){ .x = 1, .y = 1, .z = 1, })
#define VEC3I_LEFT 	((Vec3i){ .x = -1, .y = 0, .z = 0, })
#define VEC3I_RIGHT 	((Vec3i){ .x = 1, .y = 0, .z = 0, })
#define VEC3I_UP 	((Vec3i){ .x = 0, .y = -1, .z = 0, })
#define VEC3I_DOWN 	((Vec3i){ .x = 0, .y = 1, .z = 0, })


// ////// Vec2 //////
typedef union {
	struct { float x; float y; };
	float v[2];
} Vec2;

Vec2 vec2_add(Vec2 a, Vec2 b);
Vec2 vec2_sub(Vec2 a, Vec2 b);
Vec2 vec2_scale(Vec2 a, float scale);
float vec2_dot(Vec2 a, Vec2 b);
float vec2_lengthsqr(Vec2 vector);
Vec2 vec2_normalize(Vec2 vector);
Vec2 vec2_min(Vec2 a, Vec2 b);
Vec2 vec2_max(Vec2 a, Vec2 b);
void vec2_print(Vec2 vector);
#define VEC2_ZERO 	((Vec2){ .x = 0, .y = 0, })
#define VEC2_ONE 	((Vec2){ .x = 1, .y = 1, })
#define VEC2_LEFT 	((Vec2){ .x = -1, .y = 0, })
#define VEC2_RIGHT 	((Vec2){ .x = 1, .y = 0, })
#define VEC2_UP 	((Vec2){ .x = 0, .y = -1, })
#define VEC2_DOWN 	((Vec2){ .x = 0, .y = 1, })


// ////// Vec3 //////
typedef union {
	struct { float x; float y; float z; };
	float v[3];
} Vec3;

Vec3 vec3_add(Vec3 a, Vec3 b);
Vec3 vec3_sub(Vec3 a, Vec3 b);
Vec3 vec3_scale(Vec3 a, float scale);
float vec3_dot(Vec3 a, Vec3 b);
float vec3_lengthsqr(Vec3 vector);
Vec3 vec3_normalize(Vec3 vector);
Vec3 vec3_min(Vec3 a, Vec3 b);
Vec3 vec3_max(Vec3 a, Vec3 b);
void vec3_print(Vec3 vector);
#define VEC3_ZERO 	((Vec3){ .x = 0, .y = 0, .z = 0, })
#define VEC3_ONE 	((Vec3){ .x = 1, .y = 1, .z = 1, })
#define VEC3_LEFT 	((Vec3){ .x = -1, .y = 0, .z = 0, })
#define VEC3_RIGHT 	((Vec3){ .x = 1, .y = 0, .z = 0, })
#define VEC3_UP 	((Vec3){ .x = 0, .y = -1, .z = 0, })
#define VEC3_DOWN 	((Vec3){ .x = 0, .y = 1, .z = 0, })


#endif // LINALG_H
