// This file has been autogenerated using meta/math/generate.lua
#include "linalg.h"
#include <stdio.h>
#define min(a, b) (a < b) ? a : b
#define max(a, b) (a > b) ? a : b

inline float fast_inv_sqrt(float v) {
	float vhalf = 0.5f * v;
	int i = *(int*)&v;
	i = 0x5f3759df - (i >> 1);
	v = *(float*)&i;
	v = v * (1.5f - vhalf * v * v);
	return v;
}


// ////// Vec2i //////
inline Vec2i vec2i_add(Vec2i a, Vec2i b) {
	return ((Vec2i){
		.x = a.x + b.x,
		.y = a.y + b.y,
	});
}
inline Vec2i vec2i_sub(Vec2i a, Vec2i b) {
	return ((Vec2i){
		.x = a.x - b.x,
		.y = a.y - b.y,
	});
}
inline Vec2i vec2i_scale(Vec2i a, int scale) {
	return ((Vec2i){
		.x = a.x * scale,
		.y = a.y * scale,
	});
}
inline int vec2i_dot(Vec2i a, Vec2i b) {
	return (a.x * b.x) + (a.y * b.y);
}
inline int vec2i_lengthsqr(Vec2i vector) {
	return (vector.x * vector.x) + (vector.y * vector.y);
}
inline Vec2i vec2i_normalize(Vec2i vector) {
	float inv_len = fast_inv_sqrt(vec2i_lengthsqr(vector));
	return ((Vec2i){
		.x = (int)(vector.x * inv_len),
		.y = (int)(vector.y * inv_len),
	});
}
inline Vec2i vec2i_min(Vec2i a, Vec2i b) {
	return ((Vec2i){
		.x = min(a.x, b.x),
		.y = min(a.y, b.y),
	});
}
inline Vec2i vec2i_max(Vec2i a, Vec2i b) {
	return ((Vec2i){
		.x = max(a.x, b.x),
		.y = max(a.y, b.y),
	});
}
inline void vec2i_print(Vec2i vector) {
	printf("Vec2i(%d, %d)", vector.x, vector.y);
}


// ////// Vec3i //////
inline Vec3i vec3i_add(Vec3i a, Vec3i b) {
	return ((Vec3i){
		.x = a.x + b.x,
		.y = a.y + b.y,
		.z = a.z + b.z,
	});
}
inline Vec3i vec3i_sub(Vec3i a, Vec3i b) {
	return ((Vec3i){
		.x = a.x - b.x,
		.y = a.y - b.y,
		.z = a.z - b.z,
	});
}
inline Vec3i vec3i_scale(Vec3i a, int scale) {
	return ((Vec3i){
		.x = a.x * scale,
		.y = a.y * scale,
		.z = a.z * scale,
	});
}
inline int vec3i_dot(Vec3i a, Vec3i b) {
	return (a.x * b.x) + (a.y * b.y) + (a.z * b.z);
}
inline int vec3i_lengthsqr(Vec3i vector) {
	return (vector.x * vector.x) + (vector.y * vector.y) + (vector.z * vector.z);
}
inline Vec3i vec3i_normalize(Vec3i vector) {
	float inv_len = fast_inv_sqrt(vec3i_lengthsqr(vector));
	return ((Vec3i){
		.x = (int)(vector.x * inv_len),
		.y = (int)(vector.y * inv_len),
		.z = (int)(vector.z * inv_len),
	});
}
inline Vec3i vec3i_min(Vec3i a, Vec3i b) {
	return ((Vec3i){
		.x = min(a.x, b.x),
		.y = min(a.y, b.y),
		.z = min(a.z, b.z),
	});
}
inline Vec3i vec3i_max(Vec3i a, Vec3i b) {
	return ((Vec3i){
		.x = max(a.x, b.x),
		.y = max(a.y, b.y),
		.z = max(a.z, b.z),
	});
}
inline void vec3i_print(Vec3i vector) {
	printf("Vec3i(%d, %d, %d)", vector.x, vector.y, vector.z);
}


// ////// Vec2 //////
inline Vec2 vec2_add(Vec2 a, Vec2 b) {
	return ((Vec2){
		.x = a.x + b.x,
		.y = a.y + b.y,
	});
}
inline Vec2 vec2_sub(Vec2 a, Vec2 b) {
	return ((Vec2){
		.x = a.x - b.x,
		.y = a.y - b.y,
	});
}
inline Vec2 vec2_scale(Vec2 a, float scale) {
	return ((Vec2){
		.x = a.x * scale,
		.y = a.y * scale,
	});
}
inline float vec2_dot(Vec2 a, Vec2 b) {
	return (a.x * b.x) + (a.y * b.y);
}
inline float vec2_lengthsqr(Vec2 vector) {
	return (vector.x * vector.x) + (vector.y * vector.y);
}
inline Vec2 vec2_normalize(Vec2 vector) {
	float inv_len = fast_inv_sqrt(vec2_lengthsqr(vector));
	return ((Vec2){
		.x = (float)(vector.x * inv_len),
		.y = (float)(vector.y * inv_len),
	});
}
inline Vec2 vec2_min(Vec2 a, Vec2 b) {
	return ((Vec2){
		.x = min(a.x, b.x),
		.y = min(a.y, b.y),
	});
}
inline Vec2 vec2_max(Vec2 a, Vec2 b) {
	return ((Vec2){
		.x = max(a.x, b.x),
		.y = max(a.y, b.y),
	});
}
inline void vec2_print(Vec2 vector) {
	printf("Vec2(%f, %f)", vector.x, vector.y);
}


// ////// Vec3 //////
inline Vec3 vec3_add(Vec3 a, Vec3 b) {
	return ((Vec3){
		.x = a.x + b.x,
		.y = a.y + b.y,
		.z = a.z + b.z,
	});
}
inline Vec3 vec3_sub(Vec3 a, Vec3 b) {
	return ((Vec3){
		.x = a.x - b.x,
		.y = a.y - b.y,
		.z = a.z - b.z,
	});
}
inline Vec3 vec3_scale(Vec3 a, float scale) {
	return ((Vec3){
		.x = a.x * scale,
		.y = a.y * scale,
		.z = a.z * scale,
	});
}
inline float vec3_dot(Vec3 a, Vec3 b) {
	return (a.x * b.x) + (a.y * b.y) + (a.z * b.z);
}
inline float vec3_lengthsqr(Vec3 vector) {
	return (vector.x * vector.x) + (vector.y * vector.y) + (vector.z * vector.z);
}
inline Vec3 vec3_normalize(Vec3 vector) {
	float inv_len = fast_inv_sqrt(vec3_lengthsqr(vector));
	return ((Vec3){
		.x = (float)(vector.x * inv_len),
		.y = (float)(vector.y * inv_len),
		.z = (float)(vector.z * inv_len),
	});
}
inline Vec3 vec3_min(Vec3 a, Vec3 b) {
	return ((Vec3){
		.x = min(a.x, b.x),
		.y = min(a.y, b.y),
		.z = min(a.z, b.z),
	});
}
inline Vec3 vec3_max(Vec3 a, Vec3 b) {
	return ((Vec3){
		.x = max(a.x, b.x),
		.y = max(a.y, b.y),
		.z = max(a.z, b.z),
	});
}
inline void vec3_print(Vec3 vector) {
	printf("Vec3(%f, %f, %f)", vector.x, vector.y, vector.z);
}


